name: Deploy Aice PS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      action:
        description: "选择操作（deploy 或 disable）"
        required: true
        type: choice
        options:
          - deploy
          - disable
        default: deploy

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          # 可选：如需在前端打包时注入默认 key（注意会暴露在前端）
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload Nginx templates
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "deploy/nginx/*"
          target: "/tmp"
          strip_components: 2

      - name: Provision server (nginx, firewall, dir, ssl via acme.sh)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            DOMAIN="${{ secrets.SERVER_DOMAIN }}"
            EMAIL="${{ secrets.ACME_CONTACT_EMAIL }}"
            [ -z "$DOMAIN" ] && { echo "SERVER_DOMAIN secret 未设置"; exit 1; }
            APEX_DOMAIN=$(echo "$DOMAIN" | sed -E 's/^www\.//')

            mkdir -p /var/www/aice-ps
            mkdir -p /etc/nginx/ssl

            # 安装 Nginx（根据系统包管理器自动选择）并开放端口
            if command -v apt-get >/dev/null 2>&1; then
              DEBIAN_FRONTEND=noninteractive apt-get update -y
              DEBIAN_FRONTEND=noninteractive apt-get install -y nginx curl socat sed
              systemctl enable nginx || true
              if command -v ufw >/dev/null 2>&1; then
                ufw allow 80/tcp || true
                ufw allow 443/tcp || true
              fi
            elif command -v yum >/dev/null 2>&1; then
              yum install -y nginx curl socat sed || true
              systemctl enable nginx || true
              if command -v firewall-cmd >/dev/null 2>&1; then
                firewall-cmd --add-service=http --permanent || true
                firewall-cmd --add-service=https --permanent || true
                firewall-cmd --reload || true
              fi
            elif command -v dnf >/dev/null 2>&1; then
              dnf install -y nginx curl socat sed || true
              systemctl enable nginx || true
              if command -v firewall-cmd >/dev/null 2>&1; then
                firewall-cmd --add-service=http --permanent || true
                firewall-cmd --add-service=https --permanent || true
                firewall-cmd --reload || true
              fi
            fi

            # 选择 Nginx 配置路径
            if [ -d /etc/nginx/conf.d ]; then
              NGINX_CONF="/etc/nginx/conf.d/aice-ps.conf"
            else
              mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled || true
              NGINX_CONF="/etc/nginx/sites-available/aice-ps"
              ln -sf /etc/nginx/sites-available/aice-ps /etc/nginx/sites-enabled/aice-ps || true
            fi

            # 第一阶段：仅 HTTP 配置，保证 nginx 可用，供 ACME 校验
            sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__APEX__/$APEX_DOMAIN/g" /tmp/aice-ps.http.conf > "$NGINX_CONF"
            nginx -t
            systemctl restart nginx || service nginx restart || true

            # 安装 acme.sh（若未安装），并使用 webroot 为两个域名签发证书
            if [ ! -d "$HOME/.acme.sh" ]; then
              curl -s https://get.acme.sh | sh -s email=${EMAIL:-admin@${APEX_DOMAIN}}
              export PATH="$HOME/.acme.sh:$PATH"
            fi
            if [ -f "$HOME/.acme.sh/acme.sh" ]; then
              export PATH="$HOME/.acme.sh:$PATH"
              acme.sh --set-default-ca --server letsencrypt || true
              acme.sh --issue --webroot /var/www/aice-ps -d "$DOMAIN" -d "$APEX_DOMAIN" || true
              acme.sh --install-cert -d "$DOMAIN" \
                --key-file       /etc/nginx/ssl/${DOMAIN}.key \
                --fullchain-file /etc/nginx/ssl/${DOMAIN}.crt \
                --reloadcmd     "nginx -t && (systemctl reload nginx || service nginx reload || true)" || true
            else
              echo "acme.sh 未安装成功，跳过证书签发"
            fi

            # 第二阶段：启用 HTTPS + 强制跳转
            sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__APEX__/$APEX_DOMAIN/g" /tmp/aice-ps.https.conf > "$NGINX_CONF"
            nginx -t
            systemctl restart nginx || service nginx restart || true

      - name: Cleanup old static files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            mkdir -p /var/www/aice-ps
            find /var/www/aice-ps -mindepth 1 -maxdepth 1 -exec rm -rf {} +

      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "dist/**"
          target: "/var/www/aice-ps"
          strip_components: 1

      - name: Debug remote state
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            echo "== ls -la /var/www/aice-ps =="
            ls -la /var/www/aice-ps || true
            echo "== head index.html =="
            head -n 20 /var/www/aice-ps/index.html || true
            echo "== nginx -T (grep aice-ps) =="
            nginx -T 2>/dev/null | sed -n '/aice-ps/,/}/p' || true

      - name: Fix ownership, permissions and SELinux context
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            # 统一属主为 nginx 运行用户
            NGINX_USER=$(id -u www-data >/dev/null 2>&1 && echo www-data || echo nginx)
            chown -R $NGINX_USER:$NGINX_USER /var/www/aice-ps
            find /var/www/aice-ps -type d -exec chmod 755 {} +
            find /var/www/aice-ps -type f -exec chmod 644 {} +

            # 若启用 SELinux，设置正确的安全上下文
            if command -v selinuxenabled >/dev/null 2>&1 && selinuxenabled; then
              if command -v semanage >/dev/null 2>&1; then
                semanage fcontext -a -t httpd_sys_content_t "/var/www/aice-ps(/.*)?" || true
              else
                # 某些系统 semanage 未装，尝试安装
                if command -v yum >/dev/null 2>&1; then
                  yum install -y policycoreutils-python-utils || yum install -y policycoreutils-python || true
                elif command -v dnf >/dev/null 2>&1; then
                  dnf install -y policycoreutils-python-utils || true
                elif command -v apt-get >/dev/null 2>&1; then
                  apt-get update -y && apt-get install -y policycoreutils || true
                fi
                command -v semanage >/dev/null 2>&1 && semanage fcontext -a -t httpd_sys_content_t "/var/www/aice-ps(/.*)?" || true
              fi
              restorecon -Rv /var/www/aice-ps || true
            fi

      - name: Validate and restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            nginx -t
            systemctl restart nginx || service nginx restart || true 

  disable-service:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'disable'
    runs-on: ubuntu-latest
    steps:
      - name: Disable service on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            echo "== Disabling aice-ps service =="

            # 尝试禁用站点配置
            if [ -d /etc/nginx/conf.d ]; then
              [ -f /etc/nginx/conf.d/aice-ps.conf ] && mv /etc/nginx/conf.d/aice-ps.conf /etc/nginx/conf.d/aice-ps.conf.disabled || true
            else
              [ -L /etc/nginx/sites-enabled/aice-ps ] && rm -f /etc/nginx/sites-enabled/aice-ps || true
            fi

            # 尝试停止 Nginx 服务
            systemctl stop nginx || service nginx stop || true

            # 关闭常见防火墙的 80/443 端口
            if command -v ufw >/dev/null 2>&1; then
              ufw deny 80/tcp || true
              ufw deny 443/tcp || true
            fi
            if command -v firewall-cmd >/dev/null 2>&1; then
              firewall-cmd --remove-service=http --permanent || true
              firewall-cmd --remove-service=https --permanent || true
              firewall-cmd --reload || true
            fi

            echo "== Done. Service disabled. ==" 